# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop
    minecraft_version=1.21.10
    loader_version=0.17.2

# Mod Properties
	mod_version = 1.4.188-sculk.6
	maven_group = xyz.nikitacartes
	archives_base_name = sculk-carpet

# Dependencies Api
    fabric_version=0.138.4+1.21.10
    fabric_permissions_version=0.5.0
    luckperms_api_version=5.4

# Dependencies Mod
    carpet_version=1.21.10-1.4.188+v251016
    blockbot_version=2.0.6+1.21.10
    # Required for the blockbot api, but not used directly in the mod.
    kotlin_version=2.2.21